# Generates kk/src/dev_d3d_trace.cpp: a developer-only hook on every D3D library function the engine calls
# (d3d_entry_points.json), counting calls per frame and, for windows of frames, logging each call's arguments
# and the bytes of the objects it is passed or returns (see DUMP_ARGS / DUMP_RET below).
# Usage: python gen_d3d_trace.py <d3d_entry_points.json> <out .cpp>
import json
import sys

entries = json.load(open(sys.argv[1]))
# Hooked elsewhere in the port (one REX_HOOK_RAW per function).
taken = {'sub_821141D8', 'sub_82106DE0', 'sub_821074E8', 'sub_821074F8', 'sub_821074C0'}
names = [e['name'] for e in entries if e['name'] not in taken]
PRESENT = 'sub_821147B8'
assert PRESENT in names, 'present not in the entry points'

# Object dumps (brief 01: object layouts checked against memory). Function -> [(argument register, bytes)].
# Each distinct (function, register, address, contents) is logged once per window.
DUMP_ARGS = {
    'sub_82118F78': [('r5', 40)],                                # SetTexture: texture
    'sub_8210BD38': [('r5', 20)],                                # SetStreamSource: vertex buffer
    'sub_8210BE38': [('r4', 20)],                                # SetIndices: index buffer
    'sub_8210C378': [('r5', 64)],                                # SetRenderTarget: surface
    'sub_8210C6E0': [('r4', 64)],                                # SetDepthStencilSurface: surface
    'sub_82111E68': [('r4', 192)],                               # SetVertexDeclaration: declaration
    'sub_821108B8': [('r4', 256)],                               # SetVertexShader: shader
    'sub_82110C28': [('r4', 768)],                               # SetPixelShader: shader
    'sub_8210BAC8': [('r4', 24)],                                # SetViewport: D3DVIEWPORT9
    'sub_82115418': [('r5', 16)],                                # Clear: first rect
    'sub_82116178': [('r5', 16), ('r6', 40), ('r7', 8), ('r10', 16)],  # Resolve: rect, texture, point, colour
    'sub_82118B88': [('r7', 12)],                                # CreateRenderTarget: parameters
    'sub_82110C90': [('r3', 192)],                               # CreateVertexDeclaration: elements
    'sub_82111CA0': [('r3', 64)],                                # CreateVertexShader: container
    'sub_82111D90': [('r3', 64)],                                # CreatePixelShader: container
    'sub_8210C130': [],
}
# Function -> bytes of the object it returns in r3.
DUMP_RET = {
    'sub_82118B88': 64,    # CreateRenderTarget
    'sub_82118838': 64,    # GetSurfaceLevel
    'sub_82118900': 64,    # GetCubeMapSurface
    'sub_82118A68': 40,    # CreateTexture
    'sub_821092B0': 20,    # CreateVertexBuffer
    'sub_821093E0': 20,    # CreateIndexBuffer
    'sub_82110C90': 192,   # CreateVertexDeclaration
    'sub_82111CA0': 256,   # CreateVertexShader
    'sub_82111D90': 768,   # CreatePixelShader
    'sub_8210BEB8': 64,    # GetRenderTarget
    'sub_8210BF00': 64,    # GetDepthStencilSurface
}

out = []
out.append('''// Developer-only: KK_DEV_D3D_TRACE=<seconds>[,<frames>][;<seconds>[,<frames>]...] profiles the game's use
// of the XDK Direct3D library (the functions the engine calls, generated by
// native-renderer/tools/analysis/gen_d3d_trace.py from the call graph). Every call is counted per frame;
// in each window (<frames> frames, default 2, starting <seconds> after launch) every call is logged with
// its arguments (r3-r10, f1) and call site (lr), objects passed to or returned by the functions listed in
// the generator are logged as hex ("KK d3d obj:" / "KK d3d ret:", once per distinct content per window),
// and each frame ends with a histogram. The frame boundary is the engine's present call (sub_821147B8).
// KK_DEV_D3D_DUMP=<file>: the device struct (20,608 bytes) is written to <file>.<window> at each window start.
#if defined(KK_DEV_TOOLS)

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_set>
#include <vector>

#include <rex/hook.h>
#include <rex/logging.h>

namespace {

struct Entry {
  const char* name;
  std::atomic<uint32_t> frame_calls{0};
  std::atomic<uint64_t> total{0};
};

Entry g_entries[] = {
''')
for n in names:
    out.append(f'    {{"{n}"}},\n')
out.append('''};
constexpr int kCount = int(sizeof(g_entries) / sizeof(g_entries[0]));

struct Window {
  double start;
  int frames;
};
std::vector<Window> g_windows;
size_t g_next_window = 0;
std::atomic<bool> g_window{false};
int g_frames_left = 0;
uint64_t g_frame = 0;
const auto g_start = std::chrono::steady_clock::now();
std::mutex g_seen_mutex;
std::unordered_set<uint64_t> g_seen;

void Init() {
  static bool done = false;
  if (done) return;
  done = true;
  const char* v = std::getenv("KK_DEV_D3D_TRACE");
  if (!v || !*v) return;
  std::string s(v);
  size_t pos = 0;
  while (pos <= s.size()) {
    size_t end = s.find(';', pos);
    if (end == std::string::npos) end = s.size();
    std::string item = s.substr(pos, end - pos);
    if (!item.empty()) {
      Window w{std::atof(item.c_str()), 2};
      if (size_t comma = item.find(','); comma != std::string::npos)
        w.frames = std::max(1, std::atoi(item.c_str() + comma + 1));
      g_windows.push_back(w);
    }
    pos = end + 1;
  }
}

void OnCall(int i, PPCContext& ctx) {
  Entry& e = g_entries[i];
  e.frame_calls.fetch_add(1, std::memory_order_relaxed);
  e.total.fetch_add(1, std::memory_order_relaxed);
  if (g_window.load(std::memory_order_relaxed)) {
    REXLOG_INFO("KK d3d: {} lr={:08X} r3={:08X} r4={:08X} r5={:08X} r6={:08X} r7={:08X} r8={:08X} r9={:08X} r10={:08X} f1={}",
                e.name, uint32_t(ctx.lr), ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32,
                ctx.r9.u32, ctx.r10.u32, ctx.f1.f64);
  }
}

// Guest heap, stack and image ranges where the engine keeps D3D objects and argument structs.
bool Dumpable(uint32_t addr, uint32_t n) {
  if (addr & 3) return false;
  const uint64_t end = uint64_t(addr) + n;
  return (addr >= 0x40000000u && end <= 0x80000000u) || (addr >= 0x82000000u && end <= 0x84000000u);
}

void DumpObject(int i, const char* kind, const char* reg, uint32_t addr, uint32_t n, uint8_t* base) {
  if (!g_window.load(std::memory_order_relaxed) || !Dumpable(addr, n)) return;
  const uint8_t* p = base + addr;
  uint64_t h = 1469598103934665603ull;
  auto mix = [&h](uint64_t v) { h = (h ^ v) * 1099511628211ull; };
  mix(uint64_t(i));
  mix(uint64_t(reg[1]) << 8 | uint64_t(reg[2]));
  mix(addr);
  for (uint32_t k = 0; k < n; ++k) mix(p[k]);
  {
    std::lock_guard<std::mutex> lock(g_seen_mutex);
    if (!g_seen.insert(h).second) return;
  }
  static const char* hexd = "0123456789ABCDEF";
  std::string hex;
  hex.reserve(n * 2 + n / 4);
  for (uint32_t k = 0; k < n; ++k) {
    if (k && (k & 3) == 0) hex += ' ';
    hex += hexd[p[k] >> 4];
    hex += hexd[p[k] & 15];
  }
  REXLOG_INFO("KK d3d {}: {} {}={:08X} n={} {}", kind, g_entries[i].name, reg, addr, n, hex);
}

void DumpDevice(uint32_t device, uint8_t* base, size_t window) {
  const char* path = std::getenv("KK_DEV_D3D_DUMP");
  if (!path || !*path || !device) return;
  const std::string file = std::string(path) + "." + std::to_string(window);
  if (FILE* f = std::fopen(file.c_str(), "wb")) {
    std::fwrite(base + device, 1, 20608, f);
    std::fclose(f);
    REXLOG_INFO("KK d3d: device {:08X} dumped to {}", device, file);
  }
}

void OnPresent(uint32_t device, uint8_t* base) {
  Init();
  ++g_frame;
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_start).count();
  const bool window = g_window.load(std::memory_order_relaxed);
  if (window) {
    std::string hist;
    for (int i = 0; i < kCount; ++i) {
      const uint32_t n = g_entries[i].frame_calls.load(std::memory_order_relaxed);
      if (n) hist += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
    }
    REXLOG_INFO("KK d3d: frame {} end:{}", g_frame, hist);
    if (--g_frames_left <= 0) {
      g_window.store(false, std::memory_order_relaxed);
      std::vector<std::pair<uint64_t, int>> totals;
      for (int i = 0; i < kCount; ++i) totals.push_back({g_entries[i].total.load(), i});
      std::sort(totals.rbegin(), totals.rend());
      std::string s;
      for (auto& [n, i] : totals) if (n) s += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
      REXLOG_INFO("KK d3d: window end after frame {} ({:.1f} s); totals since launch:{}", g_frame, t, s);
    }
  } else if (g_next_window < g_windows.size() && t >= g_windows[g_next_window].start) {
    {
      std::lock_guard<std::mutex> lock(g_seen_mutex);
      g_seen.clear();
    }
    g_frames_left = g_windows[g_next_window].frames;
    DumpDevice(device, base, g_next_window);
    REXLOG_INFO("KK d3d: window {} start at frame {} ({:.1f} s), {} frames", g_next_window, g_frame + 1, t,
                g_frames_left);
    ++g_next_window;
    g_window.store(true, std::memory_order_relaxed);
  }
  for (int i = 0; i < kCount; ++i) g_entries[i].frame_calls.store(0, std::memory_order_relaxed);
}

}  // namespace

#define KK_D3D_HOOK(INDEX, ADDR)                     \\
  REX_EXTERN(__imp__sub_##ADDR);                     \\
  REX_HOOK_RAW(sub_##ADDR) {                         \\
    OnCall(INDEX, ctx);                              \\
    __imp__sub_##ADDR(ctx, base);                    \\
  }

#define KK_D3D_HOOK_PRESENT(INDEX, ADDR)             \\
  REX_EXTERN(__imp__sub_##ADDR);                     \\
  REX_HOOK_RAW(sub_##ADDR) {                         \\
    OnCall(INDEX, ctx);                              \\
    const uint32_t device = ctx.r3.u32;              \\
    __imp__sub_##ADDR(ctx, base);                    \\
    OnPresent(device, base);                         \\
  }

''')
for i, n in enumerate(names):
    args = [a for a in DUMP_ARGS.get(n, [])]
    ret = DUMP_RET.get(n)
    if n == PRESENT:
        out.append(f'KK_D3D_HOOK_PRESENT({i}, {n[4:]})\n')
    elif not args and not ret:
        out.append(f'KK_D3D_HOOK({i}, {n[4:]})\n')
    else:
        out.append(f'REX_EXTERN(__imp__{n});\nREX_HOOK_RAW({n}) {{\n  OnCall({i}, ctx);\n')
        for reg, size in args:
            out.append(f'  DumpObject({i}, "obj", "{reg}", ctx.{reg}.u32, {size}, base);\n')
        out.append(f'  __imp__{n}(ctx, base);\n')
        if ret:
            out.append(f'  DumpObject({i}, "ret", "r3", ctx.r3.u32, {ret}, base);\n')
        out.append('}\n')
out.append('\n#endif\n')
open(sys.argv[2], 'w', newline='\n').write(''.join(out))
print(len(names), 'hooks ->', sys.argv[2])
