# Generates kk/src/dev_d3d_trace.cpp: a developer-only hook on every D3D library function the engine calls
# (d3d_entry_points.json), counting calls per frame and, for a window of frames, logging each call's arguments.
# Usage: python gen_d3d_trace.py <d3d_entry_points.json> <out .cpp>
import json
import sys

entries = json.load(open(sys.argv[1]))
# Hooked elsewhere in the port (one REX_HOOK_RAW per function).
taken = {'sub_821141D8', 'sub_82106DE0', 'sub_821074E8', 'sub_821074F8', 'sub_821074C0'}
names = [e['name'] for e in entries if e['name'] not in taken]
PRESENT = 'sub_821147B8'
assert PRESENT in names, 'present not in the entry points'

out = []
out.append('''// Developer-only: KK_DEV_D3D_TRACE=<seconds>[,<frames>] profiles the game's use of the XDK Direct3D
// library (the functions the engine calls, generated by analysis/gen_d3d_trace.py from the call graph).
// Every call is counted per frame; <frames> frames (default 2) starting <seconds> after launch are logged
// call by call with the arguments (r3-r10, f1) and the call site (lr), and each frame ends with a
// histogram. The frame boundary is the engine's present call (sub_821147B8).
#if defined(KK_DEV_TOOLS)

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <vector>

#include <rex/hook.h>
#include <rex/logging.h>

namespace {

struct Entry {
  const char* name;
  std::atomic<uint32_t> frame_calls{0};
  std::atomic<uint64_t> total{0};
};

Entry g_entries[] = {
''')
for n in names:
    out.append(f'    {{"{n}"}},\n')
out.append('''};
constexpr int kCount = int(sizeof(g_entries) / sizeof(g_entries[0]));

std::atomic<bool> g_window{false};
int g_frames_left = 0;
double g_start_after = -1.0;
int g_frames = 2;
uint64_t g_frame = 0;
const auto g_start = std::chrono::steady_clock::now();

void Init() {
  static bool done = false;
  if (done) return;
  done = true;
  if (const char* v = std::getenv("KK_DEV_D3D_TRACE"); v && *v) {
    g_start_after = std::atof(v);
    if (const char* comma = std::strchr(v, ',')) g_frames = std::max(1, std::atoi(comma + 1));
  }
}

void OnCall(int i, PPCContext& ctx) {
  Entry& e = g_entries[i];
  e.frame_calls.fetch_add(1, std::memory_order_relaxed);
  e.total.fetch_add(1, std::memory_order_relaxed);
  if (g_window.load(std::memory_order_relaxed)) {
    REXLOG_INFO("KK d3d: {} lr={:08X} r3={:08X} r4={:08X} r5={:08X} r6={:08X} r7={:08X} r8={:08X} r9={:08X} r10={:08X} f1={}",
                e.name, uint32_t(ctx.lr), ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32,
                ctx.r9.u32, ctx.r10.u32, ctx.f1.f64);
  }
}

// KK_DEV_D3D_DUMP=<file>: the D3D device struct (20,608 bytes) written when the window starts.
void DumpDevice(uint32_t device, uint8_t* base) {
  const char* path = std::getenv("KK_DEV_D3D_DUMP");
  if (!path || !*path || !device) return;
  if (FILE* f = std::fopen(path, "wb")) {
    std::fwrite(base + device, 1, 20608, f);
    std::fclose(f);
    REXLOG_INFO("KK d3d: device {:08X} dumped to {}", device, path);
  }
}

void OnPresent(uint32_t device, uint8_t* base) {
  Init();
  ++g_frame;
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_start).count();
  const bool window = g_window.load(std::memory_order_relaxed);
  if (window) {
    std::string hist;
    for (int i = 0; i < kCount; ++i) {
      const uint32_t n = g_entries[i].frame_calls.load(std::memory_order_relaxed);
      if (n) hist += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
    }
    REXLOG_INFO("KK d3d: frame {} end:{}", g_frame, hist);
    if (--g_frames_left <= 0) {
      g_window.store(false, std::memory_order_relaxed);
      std::vector<std::pair<uint64_t, int>> totals;
      for (int i = 0; i < kCount; ++i) totals.push_back({g_entries[i].total.load(), i});
      std::sort(totals.rbegin(), totals.rend());
      std::string s;
      for (auto& [n, i] : totals) if (n) s += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
      REXLOG_INFO("KK d3d: window end after frame {} ({:.1f} s); totals since launch:{}", g_frame, t, s);
      g_start_after = -1.0;
    }
  } else if (g_start_after >= 0.0 && t >= g_start_after) {
    g_window.store(true, std::memory_order_relaxed);
    g_frames_left = g_frames;
    DumpDevice(device, base);
    REXLOG_INFO("KK d3d: window start at frame {} ({:.1f} s), {} frames", g_frame + 1, t, g_frames);
  }
  for (int i = 0; i < kCount; ++i) g_entries[i].frame_calls.store(0, std::memory_order_relaxed);
}

}  // namespace

#define KK_D3D_HOOK(INDEX, ADDR)                     \\
  REX_EXTERN(__imp__sub_##ADDR);                     \\
  REX_HOOK_RAW(sub_##ADDR) {                         \\
    OnCall(INDEX, ctx);                              \\
    __imp__sub_##ADDR(ctx, base);                    \\
  }

#define KK_D3D_HOOK_PRESENT(INDEX, ADDR)             \\
  REX_EXTERN(__imp__sub_##ADDR);                     \\
  REX_HOOK_RAW(sub_##ADDR) {                         \\
    OnCall(INDEX, ctx);                              \\
    const uint32_t device = ctx.r3.u32;              \\
    __imp__sub_##ADDR(ctx, base);                    \\
    OnPresent(device, base);                         \\
  }

''')
for i, n in enumerate(names):
    macro = 'KK_D3D_HOOK_PRESENT' if n == PRESENT else 'KK_D3D_HOOK'
    out.append(f'{macro}({i}, {n[4:]})\n')
out.append('\n#endif\n')
open(sys.argv[2], 'w', newline='\n').write(''.join(out))
print(len(names), 'hooks ->', sys.argv[2])
