// Developer-only: KK_DEV_D3D_TRACE=<seconds>[,<frames>][;<seconds>[,<frames>]...] profiles the game's use
// of the XDK Direct3D library (the functions the engine calls, generated by
// native-renderer/tools/analysis/gen_d3d_trace.py from the call graph). Every call is counted per frame;
// in each window (<frames> frames, default 2, starting <seconds> after launch) every call is logged with
// its arguments (r3-r10, f1) and call site (lr), objects passed to or returned by the functions listed in
// the generator are logged as hex ("KK d3d obj:" / "KK d3d ret:", once per distinct content per window),
// and each frame ends with a histogram. The frame boundary is the engine's present call (sub_821147B8).
// KK_DEV_D3D_TRACE_FROM=menu: the window times count from the save menu opening instead of launch.
// KK_DEV_D3D_DUMP=<file>: the device struct (20,608 bytes) is written to <file>.<window> at each window start.
// KK_DEV_TEX_CENSUS=<file> and KK_DEV_TEX_DUMP=<dir>[,<count>]: the resource census (see census below).
#if defined(KK_DEV_TOOLS)

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <rex/hook.h>
#include <rex/logging.h>

#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>  // VirtualQuery (census texture dumps)
#endif
#include "menu_hook.h"

namespace {

struct Entry {
  const char* name;
  std::atomic<uint32_t> frame_calls{0};
  std::atomic<uint64_t> total{0};
};

Entry g_entries[] = {
    {"sub_82108040"},
    {"sub_821080A0"},
    {"sub_82108120"},
    {"sub_82108178"},
    {"sub_821081E0"},
    {"sub_821083E0"},
    {"sub_821083F0"},
    {"sub_82108648"},
    {"sub_82108A58"},
    {"sub_82108B18"},
    {"sub_82108B70"},
    {"sub_82108BB0"},
    {"sub_82108BC0"},
    {"sub_82108C48"},
    {"sub_82108CB0"},
    {"sub_821091C8"},
    {"sub_82109248"},
    {"sub_821092B0"},
    {"sub_82109360"},
    {"sub_821093D0"},
    {"sub_821093E0"},
    {"sub_82109490"},
    {"sub_821094F8"},
    {"sub_8210BAC8"},
    {"sub_8210BD10"},
    {"sub_8210BD38"},
    {"sub_8210BDD8"},
    {"sub_8210BE38"},
    {"sub_8210BEB8"},
    {"sub_8210BF00"},
    {"sub_8210BF40"},
    {"sub_8210C060"},
    {"sub_8210C130"},
    {"sub_8210C378"},
    {"sub_8210C6E0"},
    {"sub_8210C8B0"},
    {"sub_8210C918"},
    {"sub_8210C990"},
    {"sub_8210C9B8"},
    {"sub_8210CA70"},
    {"sub_8210CB50"},
    {"sub_8210CB70"},
    {"sub_8210EA88"},
    {"sub_821100C8"},
    {"sub_82110300"},
    {"sub_82110448"},
    {"sub_82110590"},
    {"sub_821105E8"},
    {"sub_82110640"},
    {"sub_82110690"},
    {"sub_821106E0"},
    {"sub_821106F8"},
    {"sub_821107B0"},
    {"sub_82110868"},
    {"sub_821108B8"},
    {"sub_82110C28"},
    {"sub_82110C90"},
    {"sub_82110D50"},
    {"sub_82110D90"},
    {"sub_82110E40"},
    {"sub_82110E48"},
    {"sub_82110F48"},
    {"sub_82111CA0"},
    {"sub_82111D90"},
    {"sub_82111E68"},
    {"sub_82111EE8"},
    {"sub_82111EF0"},
    {"sub_82111EF8"},
    {"sub_82111F00"},
    {"sub_82111F28"},
    {"sub_82111F30"},
    {"sub_82111F38"},
    {"sub_821124E8"},
    {"sub_821125C0"},
    {"sub_82112630"},
    {"sub_821130B0"},
    {"sub_821130B8"},
    {"sub_82113A10"},
    {"sub_82113A18"},
    {"sub_82113A20"},
    {"sub_82113A28"},
    {"sub_82113A70"},
    {"sub_82113CD8"},
    {"sub_82113CE0"},
    {"sub_82113CE8"},
    {"sub_82113CF0"},
    {"sub_82113E70"},
    {"sub_82113E78"},
    {"sub_82113E80"},
    {"sub_821147B8"},
    {"sub_82114D10"},
    {"sub_82115418"},
    {"sub_821154C8"},
    {"sub_82115708"},
    {"sub_821159F8"},
    {"sub_82116178"},
    {"sub_82116F00"},
    {"sub_82116F98"},
    {"sub_82116FC0"},
    {"sub_82117048"},
    {"sub_821170E0"},
    {"sub_821171F0"},
    {"sub_82117838"},
    {"sub_82118558"},
    {"sub_82118828"},
    {"sub_82118838"},
    {"sub_821188E0"},
    {"sub_821188F8"},
    {"sub_821189B0"},
    {"sub_82118A68"},
    {"sub_82118B88"},
    {"sub_82118E90"},
    {"sub_82118EE8"},
    {"sub_82118F10"},
    {"sub_82118F58"},
    {"sub_82118F78"},
    {"sub_82119490"},
    {"sub_82119508"},
    {"sub_82119560"},
    {"sub_821195A8"},
    {"sub_8211ADE0"},
    {"sub_82123B08"},
    {"sub_82123B48"},
    {"sub_82123B88"},
    {"sub_82123C38"},
    {"sub_82123D08"},
    {"sub_82123DC0"},
    {"sub_82124040"},
    {"sub_821240E0"},
    {"sub_821241A8"},
    {"sub_82124388"},
    {"sub_821244D8"},
    {"sub_82124698"},
    {"sub_821247F0"},
    {"sub_82124910"},
    {"sub_82124A20"},
    {"sub_82124BD8"},
    {"sub_82124D18"},
    {"sub_82124DF8"},
    {"sub_82124EB0"},
    {"sub_82124FC0"},
    {"sub_821250A0"},
    {"sub_82125158"},
    {"sub_82125258"},
    {"sub_82125318"},
    {"sub_82125348"},
    {"sub_82125B70"},
    {"sub_82126E70"},
    {"sub_82127058"},
    {"sub_82127840"},
    {"sub_82127848"},
    {"sub_82127C78"},
    {"sub_82109E78"},
    {"sub_82109F00"},
    {"sub_82109EC8"},
    {"sub_821097C0"},
    {"sub_82109788"},
    {"sub_82109840"},
    {"sub_82109C10"},
    {"sub_82109D58"},
    {"sub_82109978"},
    {"sub_82109A10"},
    {"sub_821098E0"},
    {"sub_82109B20"},
    {"sub_82109B98"},
    {"sub_82109AA8"},
    {"sub_821097F8"},
    {"sub_82109CB0"},
    {"sub_82109D20"},
    {"sub_82109F48"},
    {"sub_82109F98"},
    {"sub_8210A018"},
    {"sub_8210A060"},
    {"sub_8210A0A8"},
    {"sub_82109FE0"},
    {"sub_8210A1E0"},
    {"sub_8210A208"},
    {"sub_8210A230"},
    {"sub_8210A118"},
    {"sub_8210A160"},
    {"sub_8210A1A8"},
    {"sub_8210A0E0"},
    {"sub_8210A258"},
    {"sub_8210A280"},
    {"sub_8210A2A8"},
    {"sub_8210A2D0"},
    {"sub_8210A618"},
    {"sub_8210A670"},
    {"sub_8210A608"},
    {"sub_8210A6C0"},
    {"sub_8210A480"},
    {"sub_8210A4B8"},
    {"sub_8210C368"},
    {"sub_8210A318"},
    {"sub_8210A3D8"},
    {"sub_8210A4E8"},
    {"sub_8210A530"},
    {"sub_8210A578"},
    {"sub_8210A5C0"},
    {"sub_8210AAA0"},
    {"sub_8210AE60"},
    {"sub_8210AE00"},
    {"sub_8210AE30"},
    {"sub_8210A710"},
    {"sub_8210A740"},
    {"sub_8210A770"},
    {"sub_8210A7A0"},
    {"sub_8210A7D0"},
    {"sub_8210A800"},
    {"sub_8210A830"},
    {"sub_8210A860"},
    {"sub_8210A888"},
    {"sub_8210A8B8"},
    {"sub_8210A8E8"},
    {"sub_8210A918"},
    {"sub_8210A948"},
    {"sub_8210A978"},
    {"sub_8210A9A8"},
    {"sub_8210A9D8"},
    {"sub_8210AAC0"},
    {"sub_8210AB20"},
    {"sub_8210ABD8"},
    {"sub_8210AC90"},
    {"sub_8210AD48"},
    {"sub_8210AE90"},
    {"sub_8210AEC8"},
    {"sub_8210AF00"},
    {"sub_8210AF28"},
    {"sub_8210AF60"},
    {"sub_8210AFA0"},
    {"sub_8210AFD0"},
    {"sub_8210B000"},
    {"sub_8210B030"},
    {"sub_8210B060"},
    {"sub_8210B098"},
    {"sub_8210B0D0"},
    {"sub_8210B108"},
    {"sub_8210B130"},
    {"sub_8210B140"},
    {"sub_8210B750"},
    {"sub_8210B7A0"},
    {"sub_8210B7F0"},
    {"sub_8210B6E0"},
    {"sub_8210B270"},
    {"sub_8210B160"},
    {"sub_8210B378"},
    {"sub_8210B540"},
    {"sub_8210B5E0"},
    {"sub_8210B420"},
    {"sub_8210B330"},
    {"sub_8210B220"},
    {"sub_8210B3D0"},
    {"sub_8210B660"},
    {"sub_8210B840"},
    {"sub_8210B498"},
    {"sub_8210B898"},
    {"sub_8210B8F0"},
    {"sub_8210B948"},
    {"sub_8210B9A0"},
    {"sub_82109EC0"},
    {"sub_82109F38"},
    {"sub_82109EF0"},
    {"sub_821097E8"},
    {"sub_821097B0"},
    {"sub_821098D0"},
    {"sub_82109CA0"},
    {"sub_82109DF8"},
    {"sub_82109A00"},
    {"sub_82109A98"},
    {"sub_82109968"},
    {"sub_82109B88"},
    {"sub_82109C00"},
    {"sub_82109B10"},
    {"sub_82109830"},
    {"sub_82109CF0"},
    {"sub_82109D48"},
    {"sub_82109F90"},
    {"sub_82109FD0"},
    {"sub_8210A050"},
    {"sub_8210A098"},
    {"sub_8210A0D0"},
    {"sub_8210A008"},
    {"sub_8210A200"},
    {"sub_8210A228"},
    {"sub_8210A250"},
    {"sub_8210A150"},
    {"sub_8210A198"},
    {"sub_8210A1D0"},
    {"sub_8210A108"},
    {"sub_8210A278"},
    {"sub_8210A2A0"},
    {"sub_8210A2C8"},
    {"sub_8210A300"},
    {"sub_8210A660"},
    {"sub_8210A6B0"},
    {"sub_8210A610"},
    {"sub_8210A700"},
    {"sub_8210A4A8"},
    {"sub_8210A4E0"},
    {"sub_8210A310"},
    {"sub_8210A3B8"},
    {"sub_8210A470"},
    {"sub_8210A528"},
    {"sub_8210A570"},
    {"sub_8210A5B8"},
    {"sub_8210A600"},
    {"sub_8210AAB8"},
    {"sub_8210AE80"},
    {"sub_8210AE20"},
    {"sub_8210AE50"},
    {"sub_8210AA00"},
    {"sub_8210AA10"},
    {"sub_8210AA20"},
    {"sub_8210AA30"},
    {"sub_8210AA40"},
    {"sub_8210AA50"},
    {"sub_8210AA60"},
    {"sub_8210AA70"},
    {"sub_8210AA80"},
    {"sub_8210AA90"},
    {"sub_8210AB10"},
    {"sub_8210ABD0"},
    {"sub_8210AC88"},
    {"sub_8210AD40"},
    {"sub_8210ADF8"},
    {"sub_8210AEB8"},
    {"sub_8210AEF0"},
    {"sub_8210AF20"},
    {"sub_8210AF50"},
    {"sub_8210AF88"},
    {"sub_8210AFC8"},
    {"sub_8210AFF8"},
    {"sub_8210B028"},
    {"sub_8210B058"},
    {"sub_8210B088"},
    {"sub_8210B0C0"},
    {"sub_8210B0F8"},
    {"sub_8210B128"},
    {"sub_8210B138"},
    {"sub_8210B150"},
    {"sub_8210B788"},
    {"sub_8210B7D8"},
    {"sub_8210B828"},
    {"sub_8210B730"},
    {"sub_8210B2F8"},
    {"sub_8210B1E8"},
    {"sub_8210B3B8"},
    {"sub_8210B5A0"},
    {"sub_8210B650"},
    {"sub_8210B488"},
    {"sub_8210B368"},
    {"sub_8210B260"},
    {"sub_8210B410"},
    {"sub_8210B6D0"},
    {"sub_8210B880"},
    {"sub_8210B4F8"},
    {"sub_8210B8D8"},
    {"sub_8210B930"},
    {"sub_8210B988"},
    {"sub_8210B9E8"},
};
constexpr int kCount = int(sizeof(g_entries) / sizeof(g_entries[0]));

struct Window {
  double start;
  int frames;
};
std::vector<Window> g_windows;
size_t g_next_window = 0;
std::atomic<bool> g_window{false};
int g_frames_left = 0;
uint64_t g_frame = 0;
const auto g_start = std::chrono::steady_clock::now();
std::mutex g_seen_mutex;
std::unordered_set<uint64_t> g_seen;
// Seconds after launch when the save menu opened (KK_DEV_D3D_TRACE_FROM=menu), or -1 before that.
std::atomic<double> g_menu_seconds{-1.0};
const bool g_from_menu = [] {
  const char* v = std::getenv("KK_DEV_D3D_TRACE_FROM");
  if (!v || std::strcmp(v, "menu") != 0) return false;
  kk::OnSaveMenuShown([] {
    g_menu_seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_start).count();
    REXLOG_INFO("KK d3d: save menu opened at {:.1f} s", g_menu_seconds.load());
  });
  return true;
}();

void Init() {
  static bool done = false;
  if (done) return;
  done = true;
  const char* v = std::getenv("KK_DEV_D3D_TRACE");
  if (!v || !*v) return;
  std::string s(v);
  size_t pos = 0;
  while (pos <= s.size()) {
    size_t end = s.find(';', pos);
    if (end == std::string::npos) end = s.size();
    std::string item = s.substr(pos, end - pos);
    if (!item.empty()) {
      Window w{std::atof(item.c_str()), 2};
      if (size_t comma = item.find(','); comma != std::string::npos)
        w.frames = std::max(1, std::atoi(item.c_str() + comma + 1));
      g_windows.push_back(w);
    }
    pos = end + 1;
  }
}

void OnCall(int i, PPCContext& ctx) {
  Entry& e = g_entries[i];
  e.frame_calls.fetch_add(1, std::memory_order_relaxed);
  e.total.fetch_add(1, std::memory_order_relaxed);
  if (g_window.load(std::memory_order_relaxed)) {
    REXLOG_INFO("KK d3d: {} lr={:08X} r3={:08X} r4={:08X} r5={:08X} r6={:08X} r7={:08X} r8={:08X} r9={:08X} r10={:08X} f1={}",
                e.name, uint32_t(ctx.lr), ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32,
                ctx.r9.u32, ctx.r10.u32, ctx.f1.f64);
  }
}

// Guest heap, stack and image ranges where the engine keeps D3D objects and argument structs.
bool Dumpable(uint32_t addr, uint32_t n) {
  if (addr & 3) return false;
  const uint64_t end = uint64_t(addr) + n;
  return (addr >= 0x40000000u && end <= 0x80000000u) || (addr >= 0x82000000u && end <= 0x84000000u);
}

void DumpObject(int i, const char* kind, const char* reg, uint32_t addr, uint32_t n, uint8_t* base) {
  if (!g_window.load(std::memory_order_relaxed) || !Dumpable(addr, n)) return;
  const uint8_t* p = base + addr;
  uint64_t h = 1469598103934665603ull;
  auto mix = [&h](uint64_t v) { h = (h ^ v) * 1099511628211ull; };
  mix(uint64_t(i));
  mix(uint64_t(reg[1]) << 8 | uint64_t(reg[2]));
  mix(addr);
  for (uint32_t k = 0; k < n; ++k) mix(p[k]);
  {
    std::lock_guard<std::mutex> lock(g_seen_mutex);
    if (!g_seen.insert(h).second) return;
  }
  static const char* hexd = "0123456789ABCDEF";
  std::string hex;
  hex.reserve(n * 2 + n / 4);
  for (uint32_t k = 0; k < n; ++k) {
    if (k && (k & 3) == 0) hex += ' ';
    hex += hexd[p[k] >> 4];
    hex += hexd[p[k] & 15];
  }
  REXLOG_INFO("KK d3d {}: {} {}={:08X} n={} {}", kind, g_entries[i].name, reg, addr, n, hex);
}

void DumpDevice(uint32_t device, uint8_t* base, size_t window) {
  const char* path = std::getenv("KK_DEV_D3D_DUMP");
  if (!path || !*path || !device) return;
  const std::string file = std::string(path) + "." + std::to_string(window);
  if (FILE* f = std::fopen(file.c_str(), "wb")) {
    std::fwrite(base + device, 1, 20608, f);
    std::fclose(f);
    REXLOG_INFO("KK d3d: device {:08X} dumped to {}", device, file);
  }
}

void OnPresent(uint32_t device, uint8_t* base) {
  Init();
  ++g_frame;
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_start).count();
  const bool window = g_window.load(std::memory_order_relaxed);
  if (window) {
    std::string hist;
    for (int i = 0; i < kCount; ++i) {
      const uint32_t n = g_entries[i].frame_calls.load(std::memory_order_relaxed);
      if (n) hist += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
    }
    REXLOG_INFO("KK d3d: frame {} end:{}", g_frame, hist);
    if (--g_frames_left <= 0) {
      g_window.store(false, std::memory_order_relaxed);
      std::vector<std::pair<uint64_t, int>> totals;
      for (int i = 0; i < kCount; ++i) totals.push_back({g_entries[i].total.load(), i});
      std::sort(totals.rbegin(), totals.rend());
      std::string s;
      for (auto& [n, i] : totals) if (n) s += std::string(" ") + g_entries[i].name + "=" + std::to_string(n);
      REXLOG_INFO("KK d3d: window end after frame {} ({:.1f} s); totals since launch:{}", g_frame, t, s);
    }
  } else if (g_next_window < g_windows.size() && (!g_from_menu || g_menu_seconds >= 0.0) &&
             t >= g_windows[g_next_window].start + (g_from_menu ? g_menu_seconds.load() : 0.0)) {
    {
      std::lock_guard<std::mutex> lock(g_seen_mutex);
      g_seen.clear();
    }
    g_frames_left = g_windows[g_next_window].frames;
    DumpDevice(device, base, g_next_window);
    REXLOG_INFO("KK d3d: window {} start at frame {} ({:.1f} s), {} frames", g_next_window, g_frame + 1, t,
                g_frames_left);
    ++g_next_window;
    g_window.store(true, std::memory_order_relaxed);
  }
  for (int i = 0; i < kCount; ++i) g_entries[i].frame_calls.store(0, std::memory_order_relaxed);
}


// ---- Resource census (brief 03) ----
// KK_DEV_TEX_CENSUS=<file>: from launch, one line per distinct thing the engine hands the library: TEX
// (SetTexture: the texture's 16-byte header and its 6 fetch-constant words at +16), RT (CreateRenderTarget
// arguments, the params words and the 64-byte surface), RSV (Resolve arguments and the destination's fetch
// constant), IB / VB (the object's 32 bytes), DECL (the declaration's first 256 bytes), CTEX / CTEXI
// (texture creation, every call), LOCK / UNLOCK (per call site), SRT / SDS (surfaces set as render target
// or depth). Distinct = a new content hash (pointers and reference counts left out where known), so the
// file stays small; each kind stops after a cap.
// KK_DEV_TEX_DUMP=<dir>[,<count>]: also writes the guest memory of distinct textures as they are first bound
// (at most 4 per format / tiling / endian / dimension combination, <count> in all, default 200) as
// <dir>/tex_<base>_<hash>.bin: "KKTX", version 2, the 6 fetch words, base bytes, mip bytes (little-endian
// header), then the base and mip regions exactly as stored (upper-bound sizes, cut at uncommitted memory).
namespace census {

struct Args {
  uint32_t r[8];  // r3..r10
  double f1;
  uint32_t lr;
};

Args Capture(const PPCContext& ctx) {
  return {{ctx.r3.u32, ctx.r4.u32, ctx.r5.u32, ctx.r6.u32, ctx.r7.u32, ctx.r8.u32, ctx.r9.u32, ctx.r10.u32},
          ctx.f1.f64,
          uint32_t(ctx.lr)};
}

enum Kind { kTex, kRt, kRsv, kIb, kVb, kDecl, kCtex, kCtexi, kLock, kUnlock, kSrt, kSds, kKinds };
const char* const kKindNames[kKinds] = {"TEX", "RT", "RSV", "IB", "VB", "DECL", "CTEX", "CTEXI", "LOCK", "UNLOCK",
                                        "SRT", "SDS"};
const int kKindCaps[kKinds] = {20000, 2000, 2000, 4000, 4000, 2000, 4000, 4000, 500, 500, 2000, 2000};

std::once_flag g_once;
bool g_on = false;
std::mutex g_mutex;
FILE* g_file = nullptr;
std::unordered_set<uint64_t> g_seen;
int g_kind_lines[kKinds] = {};
std::string g_dump_dir;
int g_dump_left = 0;
std::unordered_map<uint32_t, int> g_dump_per_combo;

void InitOnce() {
  if (const char* p = std::getenv("KK_DEV_TEX_CENSUS"); p && *p) g_file = std::fopen(p, "w");
  if (const char* d = std::getenv("KK_DEV_TEX_DUMP"); d && *d) {
    g_dump_dir = d;
    g_dump_left = 200;
    if (const size_t comma = g_dump_dir.find(','); comma != std::string::npos) {
      g_dump_left = std::atoi(g_dump_dir.c_str() + comma + 1);
      g_dump_dir.resize(comma);
    }
  }
  g_on = g_file != nullptr;
  if (g_on) REXLOG_INFO("KK d3d: resource census on");
}

bool On() {
  std::call_once(g_once, InitOnce);
  return g_on;
}

bool Ptr(uint32_t a) { return a >= 0x10000 && a < 0xFFFF0000; }

uint32_t Be32(const uint8_t* base, uint32_t addr) {
  const uint8_t* p = base + addr;
  return uint32_t(p[0]) << 24 | uint32_t(p[1]) << 16 | uint32_t(p[2]) << 8 | uint32_t(p[3]);
}

void Words(const uint8_t* base, uint32_t addr, uint32_t* out, int n) {
  for (int i = 0; i < n; ++i) out[i] = Ptr(addr) ? Be32(base, addr + 4 * i) : 0;
}

uint64_t Hash(Kind kind, const uint32_t* w, int n, uint64_t h = 0xCBF29CE484222325ull) {
  h ^= uint64_t(kind) << 56;
  for (int i = 0; i < n; ++i) {
    h ^= w[i];
    h *= 0x100000001B3ull;
  }
  return h;
}

std::string Hex(const uint32_t* w, int n) {
  std::string s;
  char b[12];
  for (int i = 0; i < n; ++i) {
    std::snprintf(b, sizeof(b), i ? " %08X" : "%08X", w[i]);
    s += b;
  }
  return s;
}

std::string Hex1(uint32_t v) { return Hex(&v, 1); }

// Under g_mutex: true (and counted) when the key is new and the kind is under its cap.
bool First(Kind kind, uint64_t key) {
  if (g_kind_lines[kind] >= kKindCaps[kind]) return false;
  if (!g_seen.insert(key).second) return false;
  ++g_kind_lines[kind];
  return true;
}

void Line(Kind kind, const Args& a, const std::string& body) {
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_start).count();
  std::fprintf(g_file, "%s t=%.2f f=%llu lr=%08X %s\n", kKindNames[kind], t, (unsigned long long)g_frame, a.lr,
               body.c_str());
  std::fflush(g_file);
}

// Block width, height and bits per texel by format (the SDK's FormatInfo table).
struct Fmt {
  uint8_t bw, bh;
  uint16_t bits;
};
const Fmt kFmts[64] = {
    {1, 1, 1},  {1, 1, 1},  {1, 1, 8},  {1, 1, 16}, {1, 1, 16}, {1, 1, 16}, {1, 1, 32},  {1, 1, 32},
    {1, 1, 8},  {1, 1, 8},  {1, 1, 16}, {2, 1, 16}, {2, 1, 16}, {1, 1, 32}, {1, 1, 32},  {1, 1, 16},
    {1, 1, 32}, {1, 1, 32}, {4, 4, 4},  {4, 4, 8},  {4, 4, 8},  {1, 1, 64}, {1, 1, 32},  {1, 1, 32},
    {1, 1, 16}, {1, 1, 32}, {1, 1, 64}, {1, 1, 16}, {1, 1, 32}, {1, 1, 64}, {1, 1, 16},  {1, 1, 32},
    {1, 1, 64}, {1, 1, 32}, {1, 1, 64}, {1, 1, 128}, {1, 1, 32}, {1, 1, 64}, {1, 1, 128}, {4, 1, 8},
    {2, 1, 16}, {1, 1, 16}, {1, 1, 32}, {1, 1, 8},  {4, 1, 8},  {1, 1, 16}, {1, 1, 16},  {1, 1, 16},
    {1, 1, 32}, {4, 4, 8},  {1, 1, 32}, {4, 4, 4},  {4, 4, 8},  {4, 4, 8},  {1, 1, 32},  {1, 1, 32},
    {1, 1, 32}, {1, 1, 96}, {4, 4, 4},  {4, 4, 4},  {4, 4, 4},  {4, 4, 4},  {1, 1, 32},  {1, 1, 32}};

uint32_t Align(uint32_t v, uint32_t a) { return (v + a - 1) / a * a; }

uint32_t NextPow2(uint32_t v) {
  uint32_t p = 1;
  while (p < v) p <<= 1;
  return p;
}

// Upper bounds of the base and mip regions (32x32-block tiles, 4 KB subresources, no mip tail packing).
void RegionSizes(const uint32_t* fc, uint32_t& base_bytes, uint32_t& mip_bytes) {
  const Fmt f = kFmts[fc[1] & 63];
  const uint32_t bpb = uint32_t(f.bits) * f.bw * f.bh / 8;
  const uint32_t dim = (fc[5] >> 9) & 3;
  uint32_t w, h, d = 1, layers = 1;
  if (dim == 0) {
    w = (fc[2] & 0xFFFFFF) + 1;
    h = 1;
  } else if (dim == 2) {
    w = (fc[2] & 0x7FF) + 1;
    h = ((fc[2] >> 11) & 0x7FF) + 1;
    d = (fc[2] >> 22) + 1;
  } else {
    w = (fc[2] & 0x1FFF) + 1;
    h = ((fc[2] >> 13) & 0x1FFF) + 1;
    layers = dim == 3 ? 6 : (((fc[1] >> 10) & 1) ? (fc[2] >> 26) + 1 : 1);
  }
  const uint32_t pitch = std::max(((fc[0] >> 22) & 0x1FF) * 32, w);
  const uint32_t slices = Align(d, dim == 2 ? 4 : 1) * layers;
  auto level_bytes = [&](uint32_t lw, uint32_t lh) {
    return Align(Align((lw + f.bw - 1) / f.bw, 32) * bpb * Align((lh + f.bh - 1) / f.bh, 32), 4096) * slices;
  };
  base_bytes = (fc[1] >> 12) ? level_bytes(pitch, h) : 0;
  mip_bytes = 0;
  if (fc[5] >> 12) {
    uint32_t levels = 0;
    for (uint32_t m = std::max({w, h, d}); m > 1; m >>= 1) ++levels;
    for (uint32_t l = 1; l <= levels; ++l)
      mip_bytes += level_bytes(std::max(NextPow2(w) >> l, 1u), std::max(NextPow2(h) >> l, 1u));
  }
}

// How many of n bytes from p are committed and readable.
size_t Readable(const uint8_t* p, size_t n) {
#if defined(_WIN32)
  size_t ok = 0;
  while (ok < n) {
    MEMORY_BASIC_INFORMATION mbi;
    if (!VirtualQuery(p + ok, &mbi, sizeof(mbi))) break;
    if (mbi.State != MEM_COMMIT || (mbi.Protect & (PAGE_NOACCESS | PAGE_GUARD)) || mbi.Protect == 0) break;
    ok = std::min(n, size_t(reinterpret_cast<const uint8_t*>(mbi.BaseAddress) + mbi.RegionSize - p));
  }
  return ok;
#else
  return n;
#endif
}

// GPU physical address of a CPU address in a physical view (0xA0000000, 0xC0000000, 0xE0000000).
uint32_t PhysicalAddress(uint32_t cpu) { return (cpu & 0x1FFFFFFFu) + (cpu >= 0xE0000000u ? 0x1000u : 0u); }

// Under g_mutex.
void DumpTexture(const uint8_t* base, const uint32_t* fc, uint64_t key) {
  if (g_dump_dir.empty() || g_dump_left <= 0) return;
  const uint32_t combo = (fc[1] & 0xFF) | ((fc[0] >> 31) << 8) | (((fc[5] >> 9) & 7) << 9);
  if (++g_dump_per_combo[combo] > 4) return;
  uint32_t base_bytes, mip_bytes;
  RegionSizes(fc, base_bytes, mip_bytes);
  if (base_bytes > (64u << 20) || mip_bytes > (64u << 20)) return;
  // The object's addresses are CPU addresses in one of the physical views; the 0xA0000000 view maps physical
  // memory from 0 and the 0xE0000000 view is 4 KB ahead of it (as SetTexture converts them: CPU 0xFFC96000 is
  // GPU 0x1FC97000). Version 1 of this dump read the low 29 bits without that page, one page early.
  const uint32_t base_phys = PhysicalAddress(fc[1] & 0xFFFFF000u), mip_phys = PhysicalAddress(fc[5] & 0xFFFFF000u);
  const uint8_t* base_ptr = base + 0xA0000000u + base_phys;
  const uint8_t* mip_ptr = base + 0xA0000000u + mip_phys;
  if (base_bytes) base_bytes = uint32_t(Readable(base_ptr, base_bytes));
  if (mip_bytes) mip_bytes = uint32_t(Readable(mip_ptr, mip_bytes));
  char name[64];
  std::snprintf(name, sizeof(name), "/tex_%08X_%016llX.bin", base_phys,
                (unsigned long long)key);
  if (FILE* f = std::fopen((g_dump_dir + name).c_str(), "wb")) {
    const uint32_t header[10] = {0x58544B4Bu /* "KKTX" */, 2, fc[0], fc[1], fc[2], fc[3], fc[4], fc[5],
                                 base_bytes, mip_bytes};
    std::fwrite(header, 4, 10, f);
    if (base_bytes) std::fwrite(base_ptr, 1, base_bytes, f);
    if (mip_bytes) std::fwrite(mip_ptr, 1, mip_bytes, f);
    std::fclose(f);
    --g_dump_left;
  }
}

void SetTexture(const Args& a, PPCContext&, uint8_t* base) {
  if (!On() || !Ptr(a.r[2])) return;
  uint32_t w[10];
  Words(base, a.r[2], w, 10);  // header (4 words) + fetch constant (6)
  const uint64_t key = Hash(kTex, w + 4, 6);
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kTex, key)) return;
  Line(kTex, a, "s=" + std::to_string(a.r[1]) + " obj=" + Hex1(a.r[2]) + " hdr=" + Hex(w, 4) + " fc=" + Hex(w + 4, 6));
  DumpTexture(base, w + 4, key);
}

void CreateRenderTarget(const Args& a, PPCContext& ctx, uint8_t* base) {
  if (!On()) return;
  uint32_t p[4], s[16];
  Words(base, a.r[4], p, 4);
  Words(base, ctx.r3.u32, s, 16);
  const uint32_t k[11] = {a.r[0], a.r[1], a.r[2], a.r[3], a.r[5], a.r[6], a.r[7], p[0], p[1], p[2], p[3]};
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kRt, Hash(kRt, k, 11))) return;
  Line(kRt, a, "args=" + Hex(a.r, 8) + " params=" + Hex(p, 4) + " ret=" + Hex1(ctx.r3.u32) + " surf=" + Hex(s, 16));
}

void Resolve(const Args& a, PPCContext&, uint8_t* base) {
  if (!On()) return;
  uint32_t rect[4], dest[10], point[2], color[4];
  Words(base, a.r[2], rect, 4);
  Words(base, a.r[3], dest, 10);
  Words(base, a.r[4], point, 2);
  Words(base, a.r[7], color, 4);
  float z = float(a.f1);
  uint32_t zbits;
  std::memcpy(&zbits, &z, 4);
  const uint32_t k[16] = {a.r[1], rect[0], rect[1], rect[2], rect[3], dest[4], dest[5], dest[6], dest[7], dest[8],
                          dest[9], point[0], point[1], a.r[5], a.r[6], zbits};
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kRsv, Hash(kRsv, k, 16))) return;
  Line(kRsv, a, "flags=" + Hex1(a.r[1]) + " rect=" + Hex(rect, 4) + " dest=" + Hex1(a.r[3]) + " fc=" + Hex(dest + 4, 6) +
                    " point=" + Hex(point, 2) + " level=" + Hex1(a.r[5]) + " slice=" + Hex1(a.r[6]) +
                    " color=" + Hex(color, 4) + " z=" + Hex1(zbits) + " args=" + Hex(a.r, 8));
}

void BufferObject(Kind kind, const Args& a, uint8_t* base, uint32_t obj, uint32_t extra) {
  if (!On() || !Ptr(obj)) return;
  uint32_t w[8];
  Words(base, obj, w, 8);
  const uint32_t k[5] = {w[4], w[5], w[6], w[7], extra};
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kind, Hash(kind, k, 5))) return;
  Line(kind, a, "obj=" + Hex1(obj) + " words=" + Hex(w, 8) + " args=" + Hex(a.r, 5));
}

void SetIndices(const Args& a, PPCContext&, uint8_t* base) { BufferObject(kIb, a, base, a.r[1], 0); }
void SetStreamSource(const Args& a, PPCContext&, uint8_t* base) {
  BufferObject(kVb, a, base, a.r[2], a.r[4] | a.r[1] << 24);
}

void SetVertexDeclaration(const Args& a, PPCContext&, uint8_t* base) {
  if (!On() || !Ptr(a.r[1])) return;
  uint32_t w[64];
  Words(base, a.r[1], w, 64);
  const uint32_t refcount = w[1];
  w[1] = 0;
  const uint64_t key = Hash(kDecl, w, 64, a.r[1]);
  w[1] = refcount;
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kDecl, key)) return;
  Line(kDecl, a, "obj=" + Hex1(a.r[1]) + " words=" + Hex(w, 64));
}

void Created(Kind kind, const Args& a, PPCContext& ctx, uint8_t* base) {
  if (!On()) return;
  uint32_t w[10];
  Words(base, ctx.r3.u32, w, 10);
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kind, Hash(kind, a.r, 8, g_kind_lines[kind]))) return;  // every call (up to the cap)
  Line(kind, a, "args=" + Hex(a.r, 8) + " ret=" + Hex1(ctx.r3.u32) + " words=" + Hex(w, 10));
}
void CreateTextureInner(const Args& a, PPCContext& ctx, uint8_t* base) { Created(kCtexi, a, ctx, base); }
void CreateTexture(const Args& a, PPCContext& ctx, uint8_t* base) { Created(kCtex, a, ctx, base); }

void LockSite(Kind kind, const Args& a, uint8_t* base) {
  if (!On()) return;
  uint32_t w[8];
  Words(base, a.r[0], w, 8);
  const uint32_t k[2] = {a.lr, w[0] & 0xFFFF0000u};
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kind, Hash(kind, k, 2))) return;
  Line(kind, a, "obj=" + Hex1(a.r[0]) + " words=" + Hex(w, 8) + " args=" + Hex(a.r, 8));
}
void Lock(const Args& a, PPCContext&, uint8_t* base) { LockSite(kLock, a, base); }
void Unlock(const Args& a, PPCContext&, uint8_t* base) { LockSite(kUnlock, a, base); }

void Surface(Kind kind, const Args& a, uint8_t* base, uint32_t obj, uint32_t index) {
  if (!On() || !Ptr(obj)) return;
  uint32_t s[16];
  Words(base, obj, s, 16);
  uint32_t k[13];
  k[0] = index;
  std::memcpy(k + 1, s + 4, 12 * 4);
  std::lock_guard<std::mutex> lock(g_mutex);
  if (!First(kind, Hash(kind, k, 13))) return;
  Line(kind, a, "index=" + std::to_string(index) + " obj=" + Hex1(obj) + " surf=" + Hex(s, 16));
}
void SetRenderTarget(const Args& a, PPCContext&, uint8_t* base) { Surface(kSrt, a, base, a.r[2], a.r[1]); }
void SetDepthStencilSurface(const Args& a, PPCContext&, uint8_t* base) { Surface(kSds, a, base, a.r[1], 0); }

}  // namespace census

}  // namespace

#define KK_D3D_HOOK(INDEX, ADDR)                     \
  REX_EXTERN(__imp__sub_##ADDR);                     \
  REX_HOOK_RAW(sub_##ADDR) {                         \
    OnCall(INDEX, ctx);                              \
    __imp__sub_##ADDR(ctx, base);                    \
  }

#define KK_D3D_HOOK_PRESENT(INDEX, ADDR)             \
  REX_EXTERN(__imp__sub_##ADDR);                     \
  REX_HOOK_RAW(sub_##ADDR) {                         \
    OnCall(INDEX, ctx);                              \
    const uint32_t device = ctx.r3.u32;              \
    __imp__sub_##ADDR(ctx, base);                    \
    OnPresent(device, base);                         \
  }

#define KK_D3D_HOOK_CENSUS(INDEX, ADDR, FN)          \
  REX_EXTERN(__imp__sub_##ADDR);                     \
  REX_HOOK_RAW(sub_##ADDR) {                         \
    OnCall(INDEX, ctx);                              \
    const census::Args args = census::Capture(ctx);  \
    __imp__sub_##ADDR(ctx, base);                    \
    census::FN(args, ctx, base);                     \
  }

KK_D3D_HOOK(0, 82108040)
KK_D3D_HOOK(1, 821080A0)
KK_D3D_HOOK(2, 82108120)
KK_D3D_HOOK(3, 82108178)
KK_D3D_HOOK(4, 821081E0)
KK_D3D_HOOK(5, 821083E0)
KK_D3D_HOOK(6, 821083F0)
KK_D3D_HOOK(7, 82108648)
KK_D3D_HOOK(8, 82108A58)
KK_D3D_HOOK(9, 82108B18)
KK_D3D_HOOK(10, 82108B70)
KK_D3D_HOOK(11, 82108BB0)
KK_D3D_HOOK(12, 82108BC0)
KK_D3D_HOOK(13, 82108C48)
KK_D3D_HOOK(14, 82108CB0)
KK_D3D_HOOK(15, 821091C8)
KK_D3D_HOOK(16, 82109248)
REX_EXTERN(__imp__sub_821092B0);
REX_HOOK_RAW(sub_821092B0) {
  OnCall(17, ctx);
  __imp__sub_821092B0(ctx, base);
  DumpObject(17, "ret", "r3", ctx.r3.u32, 20, base);
}
KK_D3D_HOOK_CENSUS(18, 82109360, Lock)
KK_D3D_HOOK_CENSUS(19, 821093D0, Unlock)
REX_EXTERN(__imp__sub_821093E0);
REX_HOOK_RAW(sub_821093E0) {
  OnCall(20, ctx);
  __imp__sub_821093E0(ctx, base);
  DumpObject(20, "ret", "r3", ctx.r3.u32, 20, base);
}
KK_D3D_HOOK(21, 82109490)
KK_D3D_HOOK(22, 821094F8)
REX_EXTERN(__imp__sub_8210BAC8);
REX_HOOK_RAW(sub_8210BAC8) {
  OnCall(23, ctx);
  DumpObject(23, "obj", "r4", ctx.r4.u32, 24, base);
  __imp__sub_8210BAC8(ctx, base);
}
KK_D3D_HOOK(24, 8210BD10)
REX_EXTERN(__imp__sub_8210BD38);
REX_HOOK_RAW(sub_8210BD38) {
  OnCall(25, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(25, "obj", "r5", ctx.r5.u32, 20, base);
  __imp__sub_8210BD38(ctx, base);
  census::SetStreamSource(census_args, ctx, base);
}
KK_D3D_HOOK(26, 8210BDD8)
REX_EXTERN(__imp__sub_8210BE38);
REX_HOOK_RAW(sub_8210BE38) {
  OnCall(27, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(27, "obj", "r4", ctx.r4.u32, 20, base);
  __imp__sub_8210BE38(ctx, base);
  census::SetIndices(census_args, ctx, base);
}
REX_EXTERN(__imp__sub_8210BEB8);
REX_HOOK_RAW(sub_8210BEB8) {
  OnCall(28, ctx);
  __imp__sub_8210BEB8(ctx, base);
  DumpObject(28, "ret", "r3", ctx.r3.u32, 64, base);
}
REX_EXTERN(__imp__sub_8210BF00);
REX_HOOK_RAW(sub_8210BF00) {
  OnCall(29, ctx);
  __imp__sub_8210BF00(ctx, base);
  DumpObject(29, "ret", "r3", ctx.r3.u32, 64, base);
}
KK_D3D_HOOK(30, 8210BF40)
KK_D3D_HOOK(31, 8210C060)
KK_D3D_HOOK(32, 8210C130)
REX_EXTERN(__imp__sub_8210C378);
REX_HOOK_RAW(sub_8210C378) {
  OnCall(33, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(33, "obj", "r5", ctx.r5.u32, 64, base);
  __imp__sub_8210C378(ctx, base);
  census::SetRenderTarget(census_args, ctx, base);
}
REX_EXTERN(__imp__sub_8210C6E0);
REX_HOOK_RAW(sub_8210C6E0) {
  OnCall(34, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(34, "obj", "r4", ctx.r4.u32, 64, base);
  __imp__sub_8210C6E0(ctx, base);
  census::SetDepthStencilSurface(census_args, ctx, base);
}
KK_D3D_HOOK(35, 8210C8B0)
KK_D3D_HOOK(36, 8210C918)
KK_D3D_HOOK(37, 8210C990)
KK_D3D_HOOK(38, 8210C9B8)
KK_D3D_HOOK(39, 8210CA70)
KK_D3D_HOOK(40, 8210CB50)
KK_D3D_HOOK(41, 8210CB70)
KK_D3D_HOOK(42, 8210EA88)
KK_D3D_HOOK(43, 821100C8)
KK_D3D_HOOK(44, 82110300)
KK_D3D_HOOK(45, 82110448)
KK_D3D_HOOK(46, 82110590)
KK_D3D_HOOK(47, 821105E8)
KK_D3D_HOOK(48, 82110640)
KK_D3D_HOOK(49, 82110690)
KK_D3D_HOOK(50, 821106E0)
KK_D3D_HOOK(51, 821106F8)
KK_D3D_HOOK(52, 821107B0)
KK_D3D_HOOK(53, 82110868)
REX_EXTERN(__imp__sub_821108B8);
REX_HOOK_RAW(sub_821108B8) {
  OnCall(54, ctx);
  DumpObject(54, "obj", "r4", ctx.r4.u32, 256, base);
  __imp__sub_821108B8(ctx, base);
}
REX_EXTERN(__imp__sub_82110C28);
REX_HOOK_RAW(sub_82110C28) {
  OnCall(55, ctx);
  DumpObject(55, "obj", "r4", ctx.r4.u32, 768, base);
  __imp__sub_82110C28(ctx, base);
}
REX_EXTERN(__imp__sub_82110C90);
REX_HOOK_RAW(sub_82110C90) {
  OnCall(56, ctx);
  DumpObject(56, "obj", "r3", ctx.r3.u32, 192, base);
  __imp__sub_82110C90(ctx, base);
  DumpObject(56, "ret", "r3", ctx.r3.u32, 192, base);
}
KK_D3D_HOOK(57, 82110D50)
KK_D3D_HOOK(58, 82110D90)
KK_D3D_HOOK(59, 82110E40)
KK_D3D_HOOK(60, 82110E48)
KK_D3D_HOOK(61, 82110F48)
REX_EXTERN(__imp__sub_82111CA0);
REX_HOOK_RAW(sub_82111CA0) {
  OnCall(62, ctx);
  DumpObject(62, "obj", "r3", ctx.r3.u32, 64, base);
  __imp__sub_82111CA0(ctx, base);
  DumpObject(62, "ret", "r3", ctx.r3.u32, 256, base);
}
REX_EXTERN(__imp__sub_82111D90);
REX_HOOK_RAW(sub_82111D90) {
  OnCall(63, ctx);
  DumpObject(63, "obj", "r3", ctx.r3.u32, 64, base);
  __imp__sub_82111D90(ctx, base);
  DumpObject(63, "ret", "r3", ctx.r3.u32, 768, base);
}
REX_EXTERN(__imp__sub_82111E68);
REX_HOOK_RAW(sub_82111E68) {
  OnCall(64, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(64, "obj", "r4", ctx.r4.u32, 192, base);
  __imp__sub_82111E68(ctx, base);
  census::SetVertexDeclaration(census_args, ctx, base);
}
KK_D3D_HOOK(65, 82111EE8)
KK_D3D_HOOK(66, 82111EF0)
KK_D3D_HOOK(67, 82111EF8)
KK_D3D_HOOK(68, 82111F00)
KK_D3D_HOOK(69, 82111F28)
KK_D3D_HOOK(70, 82111F30)
KK_D3D_HOOK(71, 82111F38)
KK_D3D_HOOK(72, 821124E8)
KK_D3D_HOOK(73, 821125C0)
KK_D3D_HOOK(74, 82112630)
KK_D3D_HOOK(75, 821130B0)
KK_D3D_HOOK(76, 821130B8)
KK_D3D_HOOK(77, 82113A10)
KK_D3D_HOOK(78, 82113A18)
KK_D3D_HOOK(79, 82113A20)
KK_D3D_HOOK(80, 82113A28)
KK_D3D_HOOK(81, 82113A70)
KK_D3D_HOOK(82, 82113CD8)
KK_D3D_HOOK(83, 82113CE0)
KK_D3D_HOOK(84, 82113CE8)
KK_D3D_HOOK(85, 82113CF0)
KK_D3D_HOOK(86, 82113E70)
KK_D3D_HOOK(87, 82113E78)
KK_D3D_HOOK(88, 82113E80)
KK_D3D_HOOK_PRESENT(89, 821147B8)
KK_D3D_HOOK(90, 82114D10)
REX_EXTERN(__imp__sub_82115418);
REX_HOOK_RAW(sub_82115418) {
  OnCall(91, ctx);
  DumpObject(91, "obj", "r5", ctx.r5.u32, 16, base);
  __imp__sub_82115418(ctx, base);
}
KK_D3D_HOOK(92, 821154C8)
KK_D3D_HOOK(93, 82115708)
KK_D3D_HOOK(94, 821159F8)
REX_EXTERN(__imp__sub_82116178);
REX_HOOK_RAW(sub_82116178) {
  OnCall(95, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(95, "obj", "r5", ctx.r5.u32, 16, base);
  DumpObject(95, "obj", "r6", ctx.r6.u32, 40, base);
  DumpObject(95, "obj", "r7", ctx.r7.u32, 8, base);
  DumpObject(95, "obj", "r10", ctx.r10.u32, 16, base);
  __imp__sub_82116178(ctx, base);
  census::Resolve(census_args, ctx, base);
}
KK_D3D_HOOK(96, 82116F00)
KK_D3D_HOOK(97, 82116F98)
KK_D3D_HOOK(98, 82116FC0)
KK_D3D_HOOK(99, 82117048)
KK_D3D_HOOK(100, 821170E0)
KK_D3D_HOOK(101, 821171F0)
KK_D3D_HOOK(102, 82117838)
KK_D3D_HOOK(103, 82118558)
KK_D3D_HOOK(104, 82118828)
REX_EXTERN(__imp__sub_82118838);
REX_HOOK_RAW(sub_82118838) {
  OnCall(105, ctx);
  __imp__sub_82118838(ctx, base);
  DumpObject(105, "ret", "r3", ctx.r3.u32, 64, base);
}
KK_D3D_HOOK(106, 821188E0)
KK_D3D_HOOK(107, 821188F8)
KK_D3D_HOOK(108, 821189B0)
REX_EXTERN(__imp__sub_82118A68);
REX_HOOK_RAW(sub_82118A68) {
  OnCall(109, ctx);
  const census::Args census_args = census::Capture(ctx);
  __imp__sub_82118A68(ctx, base);
  DumpObject(109, "ret", "r3", ctx.r3.u32, 40, base);
  census::CreateTextureInner(census_args, ctx, base);
}
REX_EXTERN(__imp__sub_82118B88);
REX_HOOK_RAW(sub_82118B88) {
  OnCall(110, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(110, "obj", "r7", ctx.r7.u32, 12, base);
  __imp__sub_82118B88(ctx, base);
  DumpObject(110, "ret", "r3", ctx.r3.u32, 64, base);
  census::CreateRenderTarget(census_args, ctx, base);
}
KK_D3D_HOOK(111, 82118E90)
KK_D3D_HOOK(112, 82118EE8)
KK_D3D_HOOK(113, 82118F10)
KK_D3D_HOOK(114, 82118F58)
REX_EXTERN(__imp__sub_82118F78);
REX_HOOK_RAW(sub_82118F78) {
  OnCall(115, ctx);
  const census::Args census_args = census::Capture(ctx);
  DumpObject(115, "obj", "r5", ctx.r5.u32, 40, base);
  __imp__sub_82118F78(ctx, base);
  census::SetTexture(census_args, ctx, base);
}
KK_D3D_HOOK(116, 82119490)
KK_D3D_HOOK(117, 82119508)
KK_D3D_HOOK(118, 82119560)
KK_D3D_HOOK(119, 821195A8)
KK_D3D_HOOK(120, 8211ADE0)
KK_D3D_HOOK(121, 82123B08)
KK_D3D_HOOK(122, 82123B48)
KK_D3D_HOOK(123, 82123B88)
KK_D3D_HOOK(124, 82123C38)
KK_D3D_HOOK(125, 82123D08)
KK_D3D_HOOK(126, 82123DC0)
KK_D3D_HOOK(127, 82124040)
KK_D3D_HOOK(128, 821240E0)
KK_D3D_HOOK(129, 821241A8)
KK_D3D_HOOK(130, 82124388)
KK_D3D_HOOK(131, 821244D8)
KK_D3D_HOOK(132, 82124698)
KK_D3D_HOOK(133, 821247F0)
KK_D3D_HOOK(134, 82124910)
KK_D3D_HOOK(135, 82124A20)
KK_D3D_HOOK(136, 82124BD8)
KK_D3D_HOOK(137, 82124D18)
KK_D3D_HOOK(138, 82124DF8)
KK_D3D_HOOK(139, 82124EB0)
KK_D3D_HOOK(140, 82124FC0)
KK_D3D_HOOK(141, 821250A0)
KK_D3D_HOOK(142, 82125158)
KK_D3D_HOOK(143, 82125258)
KK_D3D_HOOK(144, 82125318)
KK_D3D_HOOK(145, 82125348)
KK_D3D_HOOK(146, 82125B70)
KK_D3D_HOOK_CENSUS(147, 82126E70, CreateTexture)
KK_D3D_HOOK(148, 82127058)
KK_D3D_HOOK(149, 82127840)
KK_D3D_HOOK(150, 82127848)
KK_D3D_HOOK(151, 82127C78)
KK_D3D_HOOK(152, 82109E78)
KK_D3D_HOOK(153, 82109F00)
KK_D3D_HOOK(154, 82109EC8)
KK_D3D_HOOK(155, 821097C0)
KK_D3D_HOOK(156, 82109788)
KK_D3D_HOOK(157, 82109840)
KK_D3D_HOOK(158, 82109C10)
KK_D3D_HOOK(159, 82109D58)
KK_D3D_HOOK(160, 82109978)
KK_D3D_HOOK(161, 82109A10)
KK_D3D_HOOK(162, 821098E0)
KK_D3D_HOOK(163, 82109B20)
KK_D3D_HOOK(164, 82109B98)
KK_D3D_HOOK(165, 82109AA8)
KK_D3D_HOOK(166, 821097F8)
KK_D3D_HOOK(167, 82109CB0)
KK_D3D_HOOK(168, 82109D20)
KK_D3D_HOOK(169, 82109F48)
KK_D3D_HOOK(170, 82109F98)
KK_D3D_HOOK(171, 8210A018)
KK_D3D_HOOK(172, 8210A060)
KK_D3D_HOOK(173, 8210A0A8)
KK_D3D_HOOK(174, 82109FE0)
KK_D3D_HOOK(175, 8210A1E0)
KK_D3D_HOOK(176, 8210A208)
KK_D3D_HOOK(177, 8210A230)
KK_D3D_HOOK(178, 8210A118)
KK_D3D_HOOK(179, 8210A160)
KK_D3D_HOOK(180, 8210A1A8)
KK_D3D_HOOK(181, 8210A0E0)
KK_D3D_HOOK(182, 8210A258)
KK_D3D_HOOK(183, 8210A280)
KK_D3D_HOOK(184, 8210A2A8)
KK_D3D_HOOK(185, 8210A2D0)
KK_D3D_HOOK(186, 8210A618)
KK_D3D_HOOK(187, 8210A670)
KK_D3D_HOOK(188, 8210A608)
KK_D3D_HOOK(189, 8210A6C0)
KK_D3D_HOOK(190, 8210A480)
KK_D3D_HOOK(191, 8210A4B8)
KK_D3D_HOOK(192, 8210C368)
KK_D3D_HOOK(193, 8210A318)
KK_D3D_HOOK(194, 8210A3D8)
KK_D3D_HOOK(195, 8210A4E8)
KK_D3D_HOOK(196, 8210A530)
KK_D3D_HOOK(197, 8210A578)
KK_D3D_HOOK(198, 8210A5C0)
KK_D3D_HOOK(199, 8210AAA0)
KK_D3D_HOOK(200, 8210AE60)
KK_D3D_HOOK(201, 8210AE00)
KK_D3D_HOOK(202, 8210AE30)
KK_D3D_HOOK(203, 8210A710)
KK_D3D_HOOK(204, 8210A740)
KK_D3D_HOOK(205, 8210A770)
KK_D3D_HOOK(206, 8210A7A0)
KK_D3D_HOOK(207, 8210A7D0)
KK_D3D_HOOK(208, 8210A800)
KK_D3D_HOOK(209, 8210A830)
KK_D3D_HOOK(210, 8210A860)
KK_D3D_HOOK(211, 8210A888)
KK_D3D_HOOK(212, 8210A8B8)
KK_D3D_HOOK(213, 8210A8E8)
KK_D3D_HOOK(214, 8210A918)
KK_D3D_HOOK(215, 8210A948)
KK_D3D_HOOK(216, 8210A978)
KK_D3D_HOOK(217, 8210A9A8)
KK_D3D_HOOK(218, 8210A9D8)
KK_D3D_HOOK(219, 8210AAC0)
KK_D3D_HOOK(220, 8210AB20)
KK_D3D_HOOK(221, 8210ABD8)
KK_D3D_HOOK(222, 8210AC90)
KK_D3D_HOOK(223, 8210AD48)
KK_D3D_HOOK(224, 8210AE90)
KK_D3D_HOOK(225, 8210AEC8)
KK_D3D_HOOK(226, 8210AF00)
KK_D3D_HOOK(227, 8210AF28)
KK_D3D_HOOK(228, 8210AF60)
KK_D3D_HOOK(229, 8210AFA0)
KK_D3D_HOOK(230, 8210AFD0)
KK_D3D_HOOK(231, 8210B000)
KK_D3D_HOOK(232, 8210B030)
KK_D3D_HOOK(233, 8210B060)
KK_D3D_HOOK(234, 8210B098)
KK_D3D_HOOK(235, 8210B0D0)
KK_D3D_HOOK(236, 8210B108)
KK_D3D_HOOK(237, 8210B130)
KK_D3D_HOOK(238, 8210B140)
KK_D3D_HOOK(239, 8210B750)
KK_D3D_HOOK(240, 8210B7A0)
KK_D3D_HOOK(241, 8210B7F0)
KK_D3D_HOOK(242, 8210B6E0)
KK_D3D_HOOK(243, 8210B270)
KK_D3D_HOOK(244, 8210B160)
KK_D3D_HOOK(245, 8210B378)
KK_D3D_HOOK(246, 8210B540)
KK_D3D_HOOK(247, 8210B5E0)
KK_D3D_HOOK(248, 8210B420)
KK_D3D_HOOK(249, 8210B330)
KK_D3D_HOOK(250, 8210B220)
KK_D3D_HOOK(251, 8210B3D0)
KK_D3D_HOOK(252, 8210B660)
KK_D3D_HOOK(253, 8210B840)
KK_D3D_HOOK(254, 8210B498)
KK_D3D_HOOK(255, 8210B898)
KK_D3D_HOOK(256, 8210B8F0)
KK_D3D_HOOK(257, 8210B948)
KK_D3D_HOOK(258, 8210B9A0)
KK_D3D_HOOK(259, 82109EC0)
KK_D3D_HOOK(260, 82109F38)
KK_D3D_HOOK(261, 82109EF0)
KK_D3D_HOOK(262, 821097E8)
KK_D3D_HOOK(263, 821097B0)
KK_D3D_HOOK(264, 821098D0)
KK_D3D_HOOK(265, 82109CA0)
KK_D3D_HOOK(266, 82109DF8)
KK_D3D_HOOK(267, 82109A00)
KK_D3D_HOOK(268, 82109A98)
KK_D3D_HOOK(269, 82109968)
KK_D3D_HOOK(270, 82109B88)
KK_D3D_HOOK(271, 82109C00)
KK_D3D_HOOK(272, 82109B10)
KK_D3D_HOOK(273, 82109830)
KK_D3D_HOOK(274, 82109CF0)
KK_D3D_HOOK(275, 82109D48)
KK_D3D_HOOK(276, 82109F90)
KK_D3D_HOOK(277, 82109FD0)
KK_D3D_HOOK(278, 8210A050)
KK_D3D_HOOK(279, 8210A098)
KK_D3D_HOOK(280, 8210A0D0)
KK_D3D_HOOK(281, 8210A008)
KK_D3D_HOOK(282, 8210A200)
KK_D3D_HOOK(283, 8210A228)
KK_D3D_HOOK(284, 8210A250)
KK_D3D_HOOK(285, 8210A150)
KK_D3D_HOOK(286, 8210A198)
KK_D3D_HOOK(287, 8210A1D0)
KK_D3D_HOOK(288, 8210A108)
KK_D3D_HOOK(289, 8210A278)
KK_D3D_HOOK(290, 8210A2A0)
KK_D3D_HOOK(291, 8210A2C8)
KK_D3D_HOOK(292, 8210A300)
KK_D3D_HOOK(293, 8210A660)
KK_D3D_HOOK(294, 8210A6B0)
KK_D3D_HOOK(295, 8210A610)
KK_D3D_HOOK(296, 8210A700)
KK_D3D_HOOK(297, 8210A4A8)
KK_D3D_HOOK(298, 8210A4E0)
KK_D3D_HOOK(299, 8210A310)
KK_D3D_HOOK(300, 8210A3B8)
KK_D3D_HOOK(301, 8210A470)
KK_D3D_HOOK(302, 8210A528)
KK_D3D_HOOK(303, 8210A570)
KK_D3D_HOOK(304, 8210A5B8)
KK_D3D_HOOK(305, 8210A600)
KK_D3D_HOOK(306, 8210AAB8)
KK_D3D_HOOK(307, 8210AE80)
KK_D3D_HOOK(308, 8210AE20)
KK_D3D_HOOK(309, 8210AE50)
KK_D3D_HOOK(310, 8210AA00)
KK_D3D_HOOK(311, 8210AA10)
KK_D3D_HOOK(312, 8210AA20)
KK_D3D_HOOK(313, 8210AA30)
KK_D3D_HOOK(314, 8210AA40)
KK_D3D_HOOK(315, 8210AA50)
KK_D3D_HOOK(316, 8210AA60)
KK_D3D_HOOK(317, 8210AA70)
KK_D3D_HOOK(318, 8210AA80)
KK_D3D_HOOK(319, 8210AA90)
KK_D3D_HOOK(320, 8210AB10)
KK_D3D_HOOK(321, 8210ABD0)
KK_D3D_HOOK(322, 8210AC88)
KK_D3D_HOOK(323, 8210AD40)
KK_D3D_HOOK(324, 8210ADF8)
KK_D3D_HOOK(325, 8210AEB8)
KK_D3D_HOOK(326, 8210AEF0)
KK_D3D_HOOK(327, 8210AF20)
KK_D3D_HOOK(328, 8210AF50)
KK_D3D_HOOK(329, 8210AF88)
KK_D3D_HOOK(330, 8210AFC8)
KK_D3D_HOOK(331, 8210AFF8)
KK_D3D_HOOK(332, 8210B028)
KK_D3D_HOOK(333, 8210B058)
KK_D3D_HOOK(334, 8210B088)
KK_D3D_HOOK(335, 8210B0C0)
KK_D3D_HOOK(336, 8210B0F8)
KK_D3D_HOOK(337, 8210B128)
KK_D3D_HOOK(338, 8210B138)
KK_D3D_HOOK(339, 8210B150)
KK_D3D_HOOK(340, 8210B788)
KK_D3D_HOOK(341, 8210B7D8)
KK_D3D_HOOK(342, 8210B828)
KK_D3D_HOOK(343, 8210B730)
KK_D3D_HOOK(344, 8210B2F8)
KK_D3D_HOOK(345, 8210B1E8)
KK_D3D_HOOK(346, 8210B3B8)
KK_D3D_HOOK(347, 8210B5A0)
KK_D3D_HOOK(348, 8210B650)
KK_D3D_HOOK(349, 8210B488)
KK_D3D_HOOK(350, 8210B368)
KK_D3D_HOOK(351, 8210B260)
KK_D3D_HOOK(352, 8210B410)
KK_D3D_HOOK(353, 8210B6D0)
KK_D3D_HOOK(354, 8210B880)
KK_D3D_HOOK(355, 8210B4F8)
KK_D3D_HOOK(356, 8210B8D8)
KK_D3D_HOOK(357, 8210B930)
KK_D3D_HOOK(358, 8210B988)
KK_D3D_HOOK(359, 8210B9E8)

#endif
